---
  - name: copy bin file
    copy: src=p4p.bin dest=/usr/sbin/p4p owner=root group=root mode=755

  - name: copy control script
    copy: src=p4p.init dest=/etc/init.d/p4p owner=root group=root mode=755

  - name: check cache directory
    file: dest=/var/cache/p4p owner=root group=root mode=755

  - name: check cache directory for each p4port
    file: dest=/var/cache/p4p/{{ item }} owner=root group=root mode=755 state=directory
    with_items:
    - 1666
    - 1668
    - 1710
    - 1711
    - 1712
    - 1713
    - 1714
    - 1715
    - 1716
    - 1717
    - 1718
    - 1730
    - 1740
    - 1750
    - 1780
    - 1781
    - 1790
    - 7050
    - 7060
    - 7070
    - 1782

  - name: copy config file
    copy: src=p4p.cfg dest=/etc/default/p4p owner=root group=root mode=644
    notify:
    - restart p4proxy

#  - name: copy config file to repo for info
#    shell: /usr/bin/scp /etc/ansible/roles/p4proxy/files/p4p.cfg p-repo-app0.surc.kiev.ua:/home/debmirror/info_Proxy_SRK/p4p
