- name: Install MySQL server, client and other useful utilities
  apt: pkg={{ item }}
  with_items:
    - mysql-common
    - mysql-server
    - mysql-client
    - python-mysqldb
    - php5-mysql
    - mytop

- name: Change root user password on first run or when mysql.current_root_password was overrided with -e option
  mysql_user:
    name=root
    password={{ mysql.root_password }}
    priv=*.*:ALL,GRANT
    host={{ item }}
  with_items:
    - "{{ ansible_hostname }}"
    - 127.0.0.1
    - ::1
    - localhost
  ignore_errors: true

- name: Create MySQL databases
  mysql_db:
    login_user=root
    login_password={{ mysql.root_password }}
    name={{ item.key }}
    state={{ item.value.state | default('present') }}
  with_dict: mysql.databases
  when: item.value.state is undefined or item.value.state in ['absent', 'present']

- name: Create MySQL users
  mysql_user:
    login_user=root
    login_password={{ mysql.root_password }}
    name={{ item.key }}
    password={{ item.value.password }}
    priv={{ item.value.priv }}
    state={{ item.value.state | default('present') }}
  with_dict: mysql.users
