---
 - name: Install software for configure domain options
   apt: name={{ item }} state=latest update_cache=yes
   with_items:
   - likewise-open

 - name: Putting to domain
   command: /usr/bin/domainjoin-cli join {{ domain }} {{ user }} {{ pass }}

 - name: Domain name prefix
   command: /usr/bin/lwconfig AssumeDefaultDomain true

 - name: Format string user's home directory path.
   command: /usr/bin/lwconfig HomeDirTemplate "%H/%U"

 - name: Restrict access to computer
   command: /usr/bin/lwconfig RequireMembershipOf "SURC\\surc.dpi.linux"

 - name: Default shell
   command: lwconfig LoginShellTemplate "/bin/bash"
